
version: '3.6'

services:
  influxdb:
    image: influxdb:2.4-alpine
    container_name: influxdb
    restart: always
    environment:

      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=aqua-bucket
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=aqua-org
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=aqua_token

    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      aquarium-net:
        ipv4_address: 172.10.0.10

  # telegraf:
  #   image: telegraf
  #   container_name: telegraf
  #   restart: always
  #   volumes:
  #   - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #   depends_on:
  #     - influxdb
  #     - mosquitto-container
  #   links:
  #     - influxdb
  #   ports:
  #     - '8125:8125' 
  #   networks:
  #     aquarium-net:
  #       ipv4_address: 172.10.0.11


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      aquarium-net:
        ipv4_address: 172.10.0.12

  
  mosquitto-container:
    container_name: mqtt-container
    restart: always
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - 1883:1883
    networks:
      aquarium-net:
        ipv4_address: 172.10.0.13

  node-red:
    container_name: node-red-container
    build:
      context: ./nodered/
      dockerfile: Dockerfile
    image: node-red-container:latest
    ports:
      - "1880:1880"
    networks:
      aquarium-net:
        ipv4_address: 172.10.0.14
    volumes:
      - ./nodered/data:/data
    depends_on:
      - mosquitto-container
      - influxdb

  # node-red:
  #   restart: always
  #   build: docker-nodered/
  #   ports:
  #     - 1880:1880
  #   networks:
  #     aquarium-net:
  #       ipv4_address: 172.10.0.14

volumes:
  #grafana_data: 
  influxdb_data: 

networks:
  aquarium-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16