
version: '3.6'

services:
  influxdb:
    image: influxdb:2.4-alpine
    container_name: influxdb
    restart: always
    environment:

      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=aqua-bucket
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=aqua-org
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=aqua_token

    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto-container
    links:
      - influxdb
    ports:
      - '8125:8125' 


  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  
  mosquitto-container:
    restart: always
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    env_file:
      - .env
    networks:
      - local-net
    ports:
      - 1883:1883

  # node-red:
  #   image: nodered/node-red
  #   environment:
  #     - TZ=Europe/Amsterdam
  #   ports:
  #     - "1880:1880"
  #   networks:
  #     - local-net
  #   volumes:
  #     - node-red-data:/data

  node-red:
    restart: always
    build: docker-nodered/
    ports:
      - 1880:1880
    networks:
      - local-net

volumes:
  grafana_data: 
  influxdb_data: 
  node-red-data: 

networks:
  local-net: